- src/dialects/postgres.ts
Postgres driver allows to pass `ISO 8601` dates represented by a `string`, and can even take `Date` object as input as well.
Something like :
```
await kyselyDb.insertInto("checkins").values({
id: uuid,
inserted_at: new Date(),
recorded_at: "2022-05-31T18:31:02Z",
recorded_by: "fcamblor",
year: 2022,
content: JSON.stringify(otherCheckinFields)
})
```
> postgres timestamps should allow string|Date

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- src/constants/definitions.ts
- src/constants/imports.ts
- src/dialects/mysql/mysql-adapter.ts
- src/dialects/postgres/postgres-adapter.ts
- src/enums/node-type.ts
- src/nodes/expression-node.ts
- src/nodes/mapped-type-node.ts
- src/serializer.ts
- src/tests/index.test.ts
- src/tests/serializer.test.ts
- src/transformer.ts
Closes #22, closes #23, closes #24 and closes #25.
- feat: allow inserting numbers into Decimal fields
- feat: allow RawBuilder in Timestamp fields
- feat: improve `json` and `jsonb` typings
> release: 0.6.0

- package.json
Unfortunately NPM is sort of unpredictable when it comes to peer deps. I ran into this same issue with the kysely-data-api package we maintain. Yarn allows the user to cleanly specify their version but npm is strict and duplicates the package potentially breaking things.
> Use looser peer dependency requirement

- package.json
- pnpm-lock.yaml
- src/cli.ts
- src/generator.ts
- src/introspector.ts
Hey! This PR adds a new CLI option, `--ignore-pattern`, that allows users to ignore tables that match the pattern. For example:
```sh
kysely-codegen --ignore-pattern '^(secret_table|another_secret_table)$'
kysely-codegen --ignore-pattern '^_'
```
My particular use-case is I have auto-generated tables whose names start with an underscore. Currently when I run `kysely-codegen`, I need to then manually edit the generated file to remove whatever temporary tables existed at the time. With a CLI flag like this, I can ignore those tables and skip the manual edit step.
If you like this idea, let me know if the name works for you, I'm happy to adjust anything!
>  feat: add `--ignore-pattern` CLI option

- src/cli.ts
Fixed a regression in b749a677e6bfd7370559767e57e4c69746898f94 that removed newlines from `--help`'s output. This addresses #38.
> Fix CLI outputting --help on single line

- package.json
This will hopefully also handle the version 8 - as explained here - [Stack Overflow](https://stackoverflow.com/questions/47309598/make-your-npm-package-support-multiple-versions-of-peer-dependency)
> feat: updating peerdependency version of better-sqlite3

- src/dialects/sqlite/sqlite-adapter.ts
First off thanks for building this amazing tool. I'm really enjoying using it. There's only one issue I've run into and it's regarding SQLite boolean columns. In SQLite booleans are numeric types and Better SQLite3 respects that, but Kysely Codegen annotates them as strings which is inaccurate. The changes made in this PR seem to be enough to fix the problem on my end. 
Here's a patch that solves the problem if it's useful to anyone before this gets merged.
```diff
diff --git a/node_modules/kysely-codegen/dist/dialects/sqlite/sqlite-adapter.js b/node_modules/kysely-codegen/dist/dialects/sqlite/sqlite-adapter.js
index bf7bf43..4e7059e 100644
--- a/node_modules/kysely-codegen/dist/dialects/sqlite/sqlite-adapter.js
+++ b/node_modules/kysely-codegen/dist/dialects/sqlite/sqlite-adapter.js
@@ …
```
> Override type for boolean in SQLite adapter

- src/tests/e2e.test.ts
I ran into a small hicup while setting up tests in my Linux machine, this PR should fix the issue.
I assumed that this fix would be desirable rather than renaming the files, but let me know if you rather have it the other way around.
> Fix test suite for case sensitive file systems

- src/connection-string-parser.ts
Reference: #65 
As @RobinBlomberg stated:
> Good find. Perhaps `void new URL(connectionString);` isn't a good enough check to see whether the connection string is valid. [...] Perhaps that check should be removed entirely, and we'll just let the connection fail if it's invalid.
> fix: remove parsing of connection string using `URL`

- src/bin/index.ts
Workaround for https://github.com/brianc/node-postgres/issues/2907.
Currently on a Postgres database that doesn't have SSL enabled, kysely-codegen will first attempt to connect with SSL, fail, and then proceed to connect without SSL. After that it finished successfully, but it hangs before exiting before some TCP connection from the SSL attempt is still open.
After the CLI finishes successfully, let's just close the process. This saves a few annoying seconds for me.
> Exit process as soon as CLI finishes

- package.json
Hey 👋 
The library is listed as `license: none` on npmjs.com.
> add license to package.json.

- package.json
kysely-codegen works well with `mysql2@^3.0.0`, so this PR adds it to peer dependency to remove annoying incorrect peer dependency warnings.
> Add mysql2@^3.0.0 as peer dependency

- src/collections/symbol-collection.ts
Currently, tables with hyphens in their name generate interfaces with hyphens in their name.
This is handled together with table names with periods in them.
> Handle tables with hyphens in their name

- src/cli.ts
- src/connection-string-parser.ts
- src/constants/flags.ts
- src/tests/cli.test.ts
Allows CLI users to define path to their dotenv file
Fixes #92
> Add --env-file option

- README.md
- docker-compose.yml
- package.json
- src/cli.ts
- src/connection-string-parser.ts
- src/constants/constants.ts
- src/dialect-manager.ts
- src/dialects/index.ts
- src/dialects/libsql/index.ts
- src/dialects/libsql/libsql-adapter.ts
- src/dialects/libsql/libsql-dialect.ts
- src/dialects/libsql/libsql-introspector.ts
- src/tests/connection-string-parser.test.ts
- src/tests/e2e.test.ts
- src/tests/outputs/libsql.output.ts
libsql is a fork of SQLite used by Turso.tech and others. Kysely dialect for it was contributed by https://github.com/libsql/kysely-libsql and this commit adds support for it kysely-codegen.
The alternative to leverage codegen is to pull the schema of your libsql database, put it into a sqlite file and then run the codegen.
cc @honzasp from https://github.com/libsql/kysely-libsql.
> feat: support libsql/sqld

- src/dialects/postgres/postgres-adapter.ts
- src/serializer/serializer.test.ts
- src/transformer/definitions.ts
The JSON type for Postgres was wrong, as it accepts a JSON itself directly via Kysely for insertion and update, no need to convert to string
Fixes #124 
Video showing result:
https://github.com/RobinBlomberg/kysely-codegen/assets/46006784/51862d76-cc47-43da-85d9-adf9a820b07a
> Fix Postgres JSON type

- README.md
This patch adds instructions to the `README.md` file re: glob patterns with the `--include` and `--exclude` flags.
> Add include/exclude pattern instructions to README.md

- package-lock.json
- package.json
- src/core/connection-string-parser.ts
This PR adds support for expanding env variables when loading from the environment file, using `dotenv-expand`.
Closes #111
> Expand environment variables from .env

- src/cli/cli.ts
- src/cli/flags.ts
- src/core/dialect-manager.ts
- src/core/e2e.test.ts
- src/dialects/postgres/postgres-dialect.ts
- src/dialects/postgres/postgres-introspector.ts
- src/serializer/serializer.test.ts
- src/transformer/transformer.test.ts
Adds a new `--skip-domains` flag to skip domain introspection. This is useful for postgres compatible databases that don't support domains, like Materialize.
Fixes #112
I tried to follow the style in the project, and I ran the tests. Let me know if there is a better / different way to plumb the option through that you would prefer.
> Add a skip-domains flag for postgres

- package.json
Currently `kysely-bun-worker`, a package that provides a kysely sqlite dialect for bun, is set as `optional: false`. This causes unmet peer dependency warnings when installing packages if using a different dialect.
Example: yarn output
```
➤ YN0002: │ --@workspace:. doesn't provide kysely-bun-worker (pdcbd9), requested by kysely-codegen.
```
> Set kysely-bun-worker as an optional peer dep

- src/ast/export-statement-node.ts
- src/ast/index.ts
- src/ast/node-type.ts
- src/ast/runtime-enum-declaration-node.ts
- src/cli/cli.test.ts
- src/cli/cli.ts
- src/cli/flags.ts
- src/generator/generator.ts
- src/serializer/serializer.test.ts
- src/serializer/serializer.ts
- src/transformer/symbol-collection.ts
- src/transformer/transformer.test.ts
- src/transformer/transformer.ts
Resolves #115 
Support for generating enums in the format
```ts
export enum Mood {
happy = "happy",
happyOrSad = "happy_or_sad",
sad = "sad",
}
```
> feat: runtime enum support

- src/cli/cli.ts
- src/core/dialect-manager.ts
- src/dialects/postgres/postgres-dialect.ts
- src/dialects/postgres/postgres-introspector.ts
The `--domains` and `--no-domains` flags ended up backwards when the [flag name was changed](https://github.com/RobinBlomberg/kysely-codegen/commit/fea605a51e64c0c97cebc261eeb6a2d6b94178b7#diff-25768f5853544984f9e0188641fe6d70f0e5d5245c9317d80be7d3d32a71dd44R67). I replaced the internal `skipDomains` option with a `domains` option to match to cli flag, to avoid this sort of confusion in the future.
> fix: domain flag is respected

- README.md
On version `0.14.1` I was getting:
```
❯ pnpm kysely-codegen --include="public.*"
✗ Invalid flag: "include"
```
Here's the help output:
```
❯ pnpm kysely-codegen --help
kysely-codegen [options]
--camel-case         Use the Kysely CamelCasePlugin.
--dialect            Set the SQL dialect. (values: [postgres, mysql, sqlite, mssql, libsql, bun-sqlite])
--env-file           Specify the path to an environment file to use.
--exclude-pattern    Exclude tables matching the specified glob pattern. (examples: users, *.table, secrets.*, *._*)
--help, -h           Print this message.
--include-pattern    Only include tables matching the specified glob pattern. (examples: users, *.table, secrets.*, *._*)
--log-level          Set the terminal log level. (values: [debug, info, warn, error, silent], …
```
> fix flags in readme

- package.json
- pnpm-lock.yaml
Kysely 0.27.4 was released today and it now supports Tedious v18 (https://github.com/kysely-org/kysely/pull/1041), so I updated Kysely and Tedious versions in this PR.
> deps: bump Tedious to v18

- src/dialects/postgres/postgres-adapter.ts
This PR enhances the handling of PostgreSQL interval types in upsert and insert operations. Previously, the interval type was strictly managed as a number or IPostgresInterval. To improve flexibility and usability, this update allows the interval type to also be represented as a string. Using a number here seems incorrect, as I couldn't find such an option in the [PostgreSQL documentation](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT), but I have kept this possibility to maintain backward compatibility.
> Add String Option for PostgreSQL Interval Type in Upserts and Inserts

- package.json
- pnpm-lock.yaml
- src/cli/cli.test.ts
- src/cli/cli.ts
- src/cli/flags.ts
- src/generator/generator.ts
- src/serializer/serializer.test.ts
- src/serializer/serializer.ts
Thank you for the fantastic tool!
As discussed on https://github.com/RobinBlomberg/kysely-codegen/issues/32, I've added option `--singular`.
Given the schema:
```sql
CREATE TYPE user_status as ENUM ('ACTIVE', 'INACTIVE'); 
CREATE TABLE users (
id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
status user_status NOT NULL
);
```
Run with `--singular`
```
pnpm kysely-codegen --singular
```
generates:
```ts
import type { ColumnType } from "kysely";
type UserStatus = 'ACTIVE' | 'INACTIVE'
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
? ColumnType<S, I | undefined, U>
: ColumnType<T, T | undefined, T>;
export interface User {
id: Generated<string>;
status: UserStatus;
}
export interface Database {
users: User;
}
```
NOTE: It does not touch enum names and values.
> Add --singular option, close 32

- src/ast/expression-node.ts
- src/ast/index.ts
- src/ast/json-column-type-node.ts
- src/ast/node-type.ts
- src/ast/raw-expression-node.ts
- src/generator/generator.ts
- src/serializer/serializer.ts
- src/transformer/transformer.test.ts
- src/transformer/transformer.ts
This is somewhat related to #34, #75, and #30.
This follows the format in the JSON configuration issue (#34), so it should be adaptable to that. This does not implement any sort of TypeScript parsing. It will simply copy the value of the column name's override as an `IdentifierNode`. This will at least allow for simple type overrides, but I'm not entirely certain of what will and won't be supported with this.
I was also uncertain if the override in `#transformColumn` should truly override the type or if it should respect the `isNullable` or `isGenerated` parts of that. For now, I just have it as a true override which ignores those.
I have kept this as a property on the `Generator` class, and it is not included as a CLI option. I was not sure how this would be best implemented, so I left …
> Column overrides

- src/cli/cli.test.ts
- src/cli/cli.ts
- src/generator/adapter.ts
- src/generator/dialects/postgres/postgres-adapter.ts
- src/generator/dialects/postgres/postgres-dialect.ts
- src/generator/generator/generate.ts
- src/generator/transformer/transform.ts
- src/introspector/dialects/postgres/postgres-dialect.ts
- src/introspector/dialects/postgres/postgres-introspector.ts
Fixes https://github.com/RobinBlomberg/kysely-codegen/issues/155
This PR makes the `--schema` flag an array, so that you can specify it multiple times, which results in each of the listed schemas being unprefixed in the types. One obvious downside is that the relation names must all be unique, otherwise you will get type errors.
The way I'm planning to use this is by setting my search path to include several schemas, so that when tables are moved between schemas, we don't have to make code changes. This is important, because our app has to support 2 versions of the database at a time. Without this change, we have to add a conditional each time a relation promoted from one schema to another.
If this approach looks good, I'll add an example to the readme as well.
> Allow multiple default schemas

- src/introspector/dialects/postgres/postgres-introspector.ts
See related issue #196. 
The option was not passed to the Postgres inspector.
> Fix for #196: Correctly pass the partition option to the Postgres inspector

- src/generator/dialects/postgres/postgres-adapter.ts
We're currently facing issues with the timestamps due to Date not considering microseconds, which would be fixed if the type is `string`.
Related issues: #194, #123, #177
> Allow PG Timestamp to accept string as selectType.

- src/introspector/dialects/mssql/mssql-dialect.ts
Microsoft Sql Server has what are known as named instances. These use dynamic ports and are connected to using the following syntax `AdventureWorks\myInstanceName` where `AdventureWorks` is the server name and `myInstanceName` is the instance name.
The `tedious` library handles adding named instances to the connection config options through [`options.instanceName`](https://tediousjs.github.io/tedious/api-connection.html#:~:text=options.instanceName). This notes that port and instanceName are mutually exclusive (as the port is dynamic when using named instances).
This PR resolves this missing functionality by splitting the server into a server and instanceName and setting the port to undefined if the instanceName is present.
> Support Named Instances for Microsoft Sql Server

- src/cli/cli.test.ts
- src/cli/cli.ts
- src/cli/flags.ts
- src/generator/dialect-manager.ts
- src/generator/dialects/postgres/postgres-adapter.ts
- src/generator/dialects/postgres/postgres-dialect.ts
- src/generator/generator/generate.test.ts
- src/generator/generator/generate.ts
- src/generator/generator/snapshots/postgres-runtime-enums.snapshot.ts
- src/generator/generator/snapshots/postgres.snapshot.ts
- src/generator/transformer/transform.test.ts
- src/introspector/dialects/postgres/date-parser.ts
- src/introspector/dialects/postgres/postgres-dialect.ts
- src/introspector/index.ts
- src/introspector/introspector.fixtures.ts
- src/introspector/introspector.test.ts
Many people prefer to parse DATE columns as `strings` due to timezone issues with JS `Date`s. This adds a new flag, `--date-parser`, that allows the user to choose between using `Date` or `string` as the type for DATE columns.
I mostly just pattern matched against how `--numeric-parser` was implemented.
Closes #194
> feat: Add --date-parser flag to control Postgres DATE type

- README.md
Inspired by conversation inside: https://github.com/RobinBlomberg/kysely-codegen/issues/7
> docs: list current cli args

- README.md
I had to find this out by prompting the cli or reading the code, but the documentation is missing this argument, which is important if you want to use custom serializers and dialects (https://github.com/RobinBlomberg/kysely-codegen/releases/tag/0.18.0)
> Add missing cli arg "config-file" to documentation
